### ISSUE TITLE
Be slightly forgiving on dates of runs

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/results-analysis#126] opened 2022-08-26 16:01 UTC
Looking at https://wpt.fyi/runs?label=master&label=experimental&max-count=100&to=2022-08-27T00%3A00&product=chrome&product=firefox&product=safari&aligned&view=subtest you might expect the latest run of the analyses to be [36029f9](https://wpt.fyi/results?label=master&label=experimental&max-count=1&to=2022-08-27T00%3A00%3A00.000Z&product=chrome&product=firefox&product=safari&aligned=&sha=36029f913b), thereby providing our first results for STP 152.

Except, we don't, because our filtering of runs (on the wpt.fyi api side, admittedly!) excludes those three runs because the Safari run didn't start until the 26th, and therefore doesn't qualify for a run for _either_ the 25th or 26th.

On the whole, I think we should be slightly more flexible, given currently we exclude runs like this entirely (which I don't think was intended!).

**Comment by stephenmcgruer** [comment] 2022-08-26 16:05
Fwiw I did try to make this work previously (largely from the results-analysis side, it might be better fixed on the wpt.fyi side...), but ran into troubles with picking up the wrong runs when trying to make it work both for browsers that trigger frequently (Chrome, Firefox) and for browsers that trigger infrequently (WebKitGTK, Safari). Sadly I don't have much concrete advice, other than... here be dragons 😢 . But would love to see it!

**Comment by gsnedders** [comment] 2022-08-27 17:07
So we currently use e.g. https://wpt.fyi/api/runs?aligned=true&max-count=1&label=master&label=experimental&product=chrome&product=firefox&product=safari&from=2022-08-15&to=2022-08-16 to find runs for 2022-08-15.

Instead, we could use e.g. https://wpt.fyi/api/runs?aligned=true&max-count=1&label=master&label=experimental&product=chrome&product=firefox&product=safari&from=2022-08-01&to=2022-08-16, and then only consider that valid _if_ at least one of the runs has a start date on 2022-08-15.

Or did you find too many dragons?

**Comment by stephenmcgruer** [comment] 2022-08-29 13:55
I may misunderstand what the goal is here (or misunderstand the underlying stack - it's been a long time!), but I'm not clear why increasing the `from` would help finding runs that start after the `to` (which is exclusive IIRC). For example:

https://wpt.fyi/api/runs?aligned=true&max-count=1&label=master&label=experimental&product=chrome&product=firefox&product=safari&from=2022-08-25&to=2022-08-26

Is empty, because as you say the Safari run didn't start until the next day.

Straining at my memory, when I tried to tackle this previous I believe I started with pushing the `to` date back (e.g., set `from` to 2022-08-27 in the above example), but struggled with hitting double-includes where multiple days in a row would then have the same runs show up (because wpt.fyi would take the latest). I considered increasing `max-count` and then checking each set of runs' earliest `time_start` as you suggest above, but never got around to trying it.

But I think the idea is good, so please don't let me stop anyone giving it a go! I wouldn't be surprised if y'all found more success than me, or at least do a better job of writing down the reasons for failing if it comes to that 🤣 .

**Comment by gsnedders** [comment] 2022-08-29 16:27
> I may misunderstand what the goal is here (or misunderstand the underlying stack - it's been a long time!), but I'm not clear why increasing the `from` would help finding runs that start after the `to` (which is exclusive IIRC).

Right, from is inclusive, to is exclusive.

I think the confusion/misunderstanding might be the question about what date the runs found by https://wpt.fyi/api/runs?aligned=true&max-count=1&label=master&label=experimental&product=chrome&product=firefox&product=safari&from=2022-08-25&to=2022-08-27 should be attributed to. I think you were trying to make them get attributed to 2022-08-25 by increasing the `to`, whereas my (arguably more conservative) suggestion is to attribute them to 2022-08-26 by altering the `from`.

**Comment by foolip** [comment] 2022-08-30 09:24
When I've looked at this before, [this loop](https://github.com/web-platform-tests/results-analysis/blob/6a418787cd6d56d8cbc03405c73f9e91d79f89cc/lib/runs.js#L94-L97) has seemed a bit suspect to me. It _seems_ like part of the problems is caused by making one request per day, and that one of the following might fix the problem:

- Let the wpt.fyi API return lots of aligned runs instead of one at a time, and use pagination to go back as far as necessary.
- Get lots of runs for the browsers individually and do the "aligned only" logic in this code

But I suspect there's a good reason it's not like that. @stephenmcgruer do you remember, even vaguely, what problems one runs into with that approach?

**Comment by gsnedders** [comment] 2022-08-30 10:26
One obvious problem is we'll be getting lots of runs we don't care about?

**Comment by stephenmcgruer** [comment] 2022-08-30 11:46
> But I suspect there's a good reason it's not like that. @stephenmcgruer do you remember, even vaguely, what problems one runs into with that approach?

Yep, exactly what Sam said - you have to deal with *so* many runs, and you're basically re-inventing the wheel to do the aligned-only logic in the JS code. It might make more sense to do it on the wpt.fyi side, I never looked into that.

**Comment by foolip** [comment] 2022-08-30 15:27
Right, we'd get about 8x as many runs as we want, since Safari runs every 3 hours. But we'd probably make far fewer requests, right? If we keep using the `aligned` query param (option 1) that wouldn't need to be re-implemented in JS.

I'm imaging that if we have a rule like "aligned runs belong to YYYY-MM-DD if the earliest run started on YYYY-MM-DD" that would be easier to implement if we don't have to encode a limit to how late the latest run can be.

Am I missing other problems though?

**Comment by stephenmcgruer** [comment] 2022-08-30 15:30
> Am I missing other problems though?

Stability of the data for recent days, if you care about that. E.g., until all runs for a given commit with earliest start date YYYY-MM-DD are done, that commit won't be included. Then once the final run appears (on some later run of the data processing), it will suddenly become a valid choice and possibly **the** choice for YYYY-MM-DD, which may then change your data.

**Comment by gsnedders** [comment] 2022-08-30 16:17
> > Am I missing other problems though?
> 
> Stability of the data for recent days, if you care about that. E.g., until all runs for a given commit with earliest start date YYYY-MM-DD are done, that commit won't be included. Then once the final run appears (on some later run of the data processing), it will suddenly become a valid choice and possibly **the** choice for YYYY-MM-DD, which may then change your data.

We've already stopped caring about that, a while ago.

**Closed** 2023-09-15 14:00 UTC
